# Generated by Django 2.2.4 on 2019-08-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='address',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='phone',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
