# Generated by Django 2.2.4 on 2019-08-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190807_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='phone',
            field=models.TextField(max_length=20),
        ),
    ]
