# Generated by Django 2.2.4 on 2019-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190807_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='phone',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='address',
            field=models.TextField(),
        ),
    ]
