# Generated by Django 2.2.4 on 2019-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20190807_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='address',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
