# Generated by Django 2.2.4 on 2019-08-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20190807_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='address',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
